"""
SceneGraph — a structured knowledge graph for a single scene.

Instead of treating a scene as flat (location + character list),
the SceneGraph captures *relationships* between every entity present:

    Scene: Forest
        ├── John     (character, holds: Sword, position: center)
        ├── Monster  (character, behind: Cabin)
        ├── Sword    (object, held_by: John, state: glowing)
        ├── Cabin    (environment_element, position: background-right)
        └── Moon     (environment_element, lights: Forest, position: upper-left)

Every shot then samples from this graph to decide:
  • Which entities appear in frame
  • What relationship exists between them (enables IP-Adapter selection)
  • What state each entity is in (enables continuity checking)
"""
from __future__ import annotations

from typing import Dict, List, Optional
from pydantic import BaseModel, Field
from enum import Enum


class EntityType(str, Enum):
    CHARACTER = "character"
    OBJECT = "object"
    ENVIRONMENT = "environment"
    LOCATION = "location"
    ANIMAL = "animal"
    VEHICLE = "vehicle"


class EntityState(BaseModel):
    """Current observable state of an entity in this scene."""
    is_visible: bool = True
    position: str = ""           # 'foreground-left', 'background-right', 'center', etc.
    emotional_state: str = ""    # For characters: current emotion
    physical_state: str = ""     # 'standing', 'crouching', 'flying', 'wounded', etc.
    costume_key: str = "default" # Wardrobe lock reference
    held_items: List[str] = Field(default_factory=list)     # entity IDs of held objects
    damage_notes: str = ""       # 'cut on cheek', 'torn sleeve'
    lighting_on_entity: str = "" # 'rim lit blue', 'backlit', 'in shadow'


class SceneEntity(BaseModel):
    """A single entity (character, object, environment element) in the scene graph."""
    entity_id: str
    entity_type: EntityType
    display_name: str = ""
    state: EntityState = Field(default_factory=EntityState)
    character_profile_id: Optional[str] = None  # Links to StoryBible.characters[id]
    ip_adapter_ref_path: str = ""               # Path to reference image for this entity


class Relationship(BaseModel):
    """A directed relationship between two entities."""
    from_entity_id: str
    relation: str
    """
    Semantic relationship type:
      'holds', 'faces', 'behind', 'in_front_of', 'lights',
      'threatens', 'protects', 'observes', 'approaches', 'flees_from'
    """
    to_entity_id: str
    strength: float = 1.0  # 0.0 – 1.0, used to prioritize in composition


class SceneGraph(BaseModel):
    """
    Structured knowledge graph for one scene.

    Generated by: SceneGraphBuilderStage
    Consumed by: StoryboardPlannerStage, CompositionPlannerStage, PromptCompilerStage
    """
    scene_id: str
    location_id: str = ""

    entities: Dict[str, SceneEntity] = Field(default_factory=dict)
    """entity_id → SceneEntity"""

    relationships: List[Relationship] = Field(default_factory=list)

    ambient_conditions: Dict[str, str] = Field(default_factory=dict)
    """Global scene conditions: {'weather': 'rain', 'time': 'night', 'lighting': 'moonlit'}"""

    def get_characters(self) -> List[SceneEntity]:
        return [e for e in self.entities.values() if e.entity_type == EntityType.CHARACTER]

    def get_objects(self) -> List[SceneEntity]:
        return [e for e in self.entities.values() if e.entity_type == EntityType.OBJECT]

    def get_relationships_for(self, entity_id: str) -> List[Relationship]:
        return [r for r in self.relationships if r.from_entity_id == entity_id]

    def describe_composition(self, entity_ids: List[str]) -> str:
        """
        Generate a natural-language composition hint from the graph
        for a subset of entities (the ones appearing in a given shot).
        """
        if not entity_ids:
            return ""

        hints = []
        for entity_id in entity_ids:
            entity = self.entities.get(entity_id)
            if not entity:
                continue
            state = entity.state
            if state.position:
                hints.append(f"{entity.display_name} positioned {state.position}")
            for rel in self.get_relationships_for(entity_id):
                target = self.entities.get(rel.to_entity_id)
                if target and rel.to_entity_id in entity_ids:
                    hints.append(f"{entity.display_name} {rel.relation} {target.display_name}")

        return ", ".join(hints)


class SceneGraphManifest(BaseModel):
    """Collection of scene graphs for all scenes in the novel."""
    graphs: Dict[str, SceneGraph] = Field(default_factory=dict)
    """scene_id → SceneGraph"""

    generator: str = "SceneGraphBuilderStage"
    schema_version: str = "1.0"

    def get(self, scene_id: str) -> Optional[SceneGraph]:
        return self.graphs.get(scene_id)
