"""
Hierarchical Visual Style Bible.

Implements the four-level style inheritance system:

    GlobalStyle
        └── ChapterStyle
                └── SceneStyle
                        └── ShotStyle

Every prompt inherits from Global → Chapter → Scene → Shot, with more
specific levels overriding only the fields they define.

This single source of truth ensures visual consistency across thousands
of generated frames without per-prompt style drift.
"""
from __future__ import annotations

from typing import Dict, List, Optional
from pydantic import BaseModel, Field


class StyleTokenSet(BaseModel):
    """
    A composable block of prompt tokens.
    Fields left as empty string are inherited from parent level.
    """
    line_art: str = ""
    shading: str = ""
    color_palette: str = ""
    face_style: str = ""
    background_style: str = ""
    lighting: str = ""
    quality_tokens: str = ""
    negative_tokens: str = ""
    extra_positive: str = ""


class GlobalStyle(StyleTokenSet):
    """
    Project-wide immutable style. Applied to every single shot.
    Set once at the start of the pipeline by VisualStyleBibleStage.
    """
    style_name: str = "korean_manhwa_cinematic"
    line_art: str = "bold clean lineart, thick outlines, sharp crisp edges, Korean manhwa style"
    shading: str = "cel-shaded with soft gradient shadows, ambient occlusion, flat color blocks"
    color_palette: str = "highly saturated vibrant palette, strong local color contrast"
    face_style: str = "manhwa facial proportions, large expressive eyes, sharp jawline, smooth skin"
    background_style: str = "semi-detailed backgrounds, architectural precision, depth blur behind subject"
    lighting: str = "dramatic three-point lighting, strong rim light, deep cast shadows"
    quality_tokens: str = "masterpiece, best quality, ultra-detailed, 8k resolution, sharp focus, professional illustration"
    negative_tokens: str = (
        "blurry, low quality, bad anatomy, extra fingers, missing fingers, "
        "watermark, text, noise, grain, jpeg artifacts, ugly, deformed, "
        "3d render, photorealistic, photography, western comic style, "
        "out of frame, duplicate, cropped"
    )


class ChapterStyle(StyleTokenSet):
    """
    Per-chapter style override. Inherits from GlobalStyle.
    Override only the fields that change for this chapter.
    Example: Chapter 3 is 'warm golden tones' to reflect the flashback arc.
    """
    chapter_index: int = 0
    color_palette: str = ""   # Empty = inherit from global
    lighting: str = ""


class SceneStyle(StyleTokenSet):
    """
    Per-scene style override. Inherits from ChapterStyle → GlobalStyle.
    Example: This scene is set in rain with cold blue lighting.
    """
    scene_id: str = ""
    weather_tokens: str = ""
    time_of_day_tokens: str = ""
    color_palette: str = ""
    lighting: str = ""


class ShotStyle(StyleTokenSet):
    """
    Per-shot style override. Inherits from SceneStyle → ChapterStyle → GlobalStyle.
    Example: This specific shot has a 'blue rim light' for the sword reveal.
    """
    shot_id: str = ""
    extra_positive: str = ""  # Shot-specific accent tokens


class VisualStyleBible(BaseModel):
    """
    The immutable style source of truth for the entire project.

    Generated by: VisualStyleBibleStage
    Consumed by: PromptCompilerStage (for every single shot)
    Serialized to: workspace/manifests/style_bible.json
    """
    global_style: GlobalStyle = Field(default_factory=GlobalStyle)
    chapter_styles: Dict[int, ChapterStyle] = Field(default_factory=dict)
    scene_styles: Dict[str, SceneStyle] = Field(default_factory=dict)
    shot_styles: Dict[str, ShotStyle] = Field(default_factory=dict)

    generator: str = "VisualStyleBibleStage"
    schema_version: str = "1.0"

    def resolve(
        self,
        chapter_index: Optional[int] = None,
        scene_id: Optional[str] = None,
        shot_id: Optional[str] = None,
    ) -> "ResolvedStyle":
        """
        Resolve the final style tokens for a shot by merging the four levels.
        More specific levels override less specific ones for non-empty fields only.
        """
        resolved = ResolvedStyle(
            line_art=self.global_style.line_art,
            shading=self.global_style.shading,
            color_palette=self.global_style.color_palette,
            face_style=self.global_style.face_style,
            background_style=self.global_style.background_style,
            lighting=self.global_style.lighting,
            quality_tokens=self.global_style.quality_tokens,
            negative_tokens=self.global_style.negative_tokens,
            extra_positive=self.global_style.extra_positive,
        )

        # Chapter override
        if chapter_index is not None and chapter_index in self.chapter_styles:
            cs = self.chapter_styles[chapter_index]
            resolved = _merge(resolved, cs)

        # Scene override
        if scene_id and scene_id in self.scene_styles:
            ss = self.scene_styles[scene_id]
            resolved = _merge(resolved, ss)

        # Shot override
        if shot_id and shot_id in self.shot_styles:
            shs = self.shot_styles[shot_id]
            resolved = _merge(resolved, shs)

        return resolved

    def build_positive_prefix(
        self,
        chapter_index: Optional[int] = None,
        scene_id: Optional[str] = None,
        shot_id: Optional[str] = None,
    ) -> str:
        """Return the resolved positive-prompt style prefix for a shot."""
        r = self.resolve(chapter_index, scene_id, shot_id)
        parts = [p for p in [
            r.line_art, r.shading, r.color_palette,
            r.face_style, r.background_style, r.lighting,
            r.quality_tokens, r.extra_positive,
        ] if p]
        return ", ".join(parts)

    def build_negative_prefix(
        self,
        chapter_index: Optional[int] = None,
        scene_id: Optional[str] = None,
        shot_id: Optional[str] = None,
    ) -> str:
        return self.resolve(chapter_index, scene_id, shot_id).negative_tokens


class ResolvedStyle(StyleTokenSet):
    """Fully resolved style tokens for a single shot. Read-only output of resolve()."""


def _merge(base: ResolvedStyle, override: StyleTokenSet) -> ResolvedStyle:
    """Override non-empty fields from `override` into a copy of `base`."""
    data = base.model_dump()
    for field, value in override.model_dump().items():
        if value:  # Only override if the field is non-empty
            data[field] = value
    return ResolvedStyle(**data)
